### PR TITLE
Adding 4 More Questions

### PR DESCRIPTION
**Pull request by dalyw01**

### CODE REVIEW

**Review by tkavlearning — COMMENTED** [review]
10/10 Would look at a PR again

**Review by nataguiar-sqsp — COMMENTED** [review]
GREAT questions! Well done, Mr Daly!

**Review by tweigelt-sqsp — APPROVED** [review]
Shipt it :-D

**Review by mwall01 — APPROVED** [review]
#nit a lot of what questions

**Comment by dalyw01** [comment]
SHIPPING

**Pull request merged**
