### PR TITLE
chore: removed used questions

### PR DESCRIPTION
**Pull request by tweigelt-sqsp**
Need some help here if I caught them all ...

### CODE REVIEW

**Review by louisenoone — APPROVED** [review]
Looks like we need to add some new questions too!

**Review by nking02 — APPROVED** [review]

**Comment by tweigelt-sqsp** [comment]
> Looks like we need to add some new questions too!

New Year's resolution 🎉

**Comment by tkavlearning** [comment]
I vote for a xmas themed Wall with some holidays questions!

**Review by dalyw01 — APPROVED** [review]

**Comment by dalyw01** [comment]
Might need a refresh in general for 2025? 🤔

**Pull request merged**
